reservadjango/accounts/urls.py
from django.urls import path
from .views import SignUpView, login_view, email_check, PasswordsChangeView, pass_success, update_user,update_user_info
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name = "signup"),
    path("login/", login_view, name = "login"),

    path("update_user/", update_user, name = "update_user"),
    path("user_info/", update_user_info, name = "update_user_info"),
    
    path("email_check/", email_check, name = "email_check"),
    
    path('password_change/', PasswordsChangeView.as_view(template_name='registration/password_change.html')),
    path('password_change/done/', pass_success),
    

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset.html'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name="password_reset_complete"),
    ]

reservadjango/cart/urls.py
from django.urls import path
from .views import cart_summary, cart_add, cart_delete, cart_update
from django.contrib.auth import views as auth_views

app_name = 'cart'

urlpatterns = [
    path('', cart_summary, name="cart_summary"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    path('update/', cart_update, name="cart_update"),

]

reservadjango/payment/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import TemplateView  # new
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

app_name = 'payment'

urlpatterns = [
    path("payment_success/", views.payment_success, name = "payment_success"),
    path("billing_info/", views.billing_info, name="billing_info"),
    path("checkout/", views.checkout, name="checkout"),
    path("payment_method/", views.payment_method, name="payment_method"),
    path("process_order", views.process_order, name="process_order"),
]

reservadjango/reservadjango/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import TemplateView  # new
from django.contrib.auth.decorators import login_required
from .views import index, servicio, categoria, search, reservar, filter_products, all_services, mis_reservas
from . import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("cart/", include ("cart.urls")),
    path("payment/", include ("payment.urls")),
    path("", index, name="index"),
    path("reserva/", reservar, name="reserva"),
    path("mis_reservas/", mis_reservas, name="mis_reservas"),
    path("obtener_horas/", views.obtener_horas, name="obtener_horas"),
    path("servicio/<int:pk>", servicio, name ="servicio_detalle"),
    path("categoria/<str:foo>", categoria, name = "categoria"),
    path("search/", search, name='search'),
    path("filter_products/", filter_products, name='filter_products'),
    path("all_services/", all_services, name='all_services'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

reservadjango/reservadjango/models.py
from django.db import models
from datetime import datetime, timedelta
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre

class Servicio(models.Model):
    nombre = models.CharField(max_length = 30)
    precio = models.IntegerField(default=0)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, default=1)
    imagen = models.ImageField(upload_to='media/servicios/', default='', blank=True)
    #SALES
    descuento = models.BooleanField(default=False)
    precio_descuento =models.DecimalField(default=0, decimal_places=2, max_digits=6)
    
    def __str__(self):
        return self.nombre


class Reserva(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length = 50,null=False)
    servicio = models.CharField(max_length = 30, null=False)
    fecha = models.DateTimeField(null=False)
    hora = models.TimeField(null=False)
    contacto = models.IntegerField(default='', blank=True, null=True)

    def __str__(self):
        return f"{self.nombre}, {self.servicio}, {str(self.fecha)}, {str(self.hora)}"
    
    def reservas_mes():
        return Reserva.objects.filter(fecha__gt = datetime.now()-timedelta(days=30))
    

reservadjango/reservadjango/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse
import datetime
from . import google_calendar
import locale
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Servicio, Categoria, Reserva
from django.utils import timezone


locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')


def reservar(request):
    current_datetime = datetime.datetime.now()
    calendar_manager = google_calendar.GoogleCalendarManager()
    busy_hours, available_hours = calendar_manager.list_busy_available_events(current_datetime)

    try:
        nombre = request.user.nombre.capitalize()
        apellido = request.user.apellido.capitalize()
        telefono = request.user.telefono
    except AttributeError:
        pass

    if request.method == 'POST':
        user = request.user
        
        if not request.user.is_authenticated:
            return JsonResponse({'error_message': 'Debes iniciar sesión para realizar una reserva.'})

        print(nombre, apellido ,telefono)
        fecha = request.POST.get('fecha')
        hora = request.POST.get('hora')
        servicio = request.POST.get('servicio')
        
        if nombre =="Ingrese su nombre" or nombre == None or nombre =='' or telefono == "Ingrese un teléfono de contacto" or telefono == None or telefono == '' or hora == "Elija una hora..." or hora =='' or servicio == None or servicio =='' or servicio == "Elija un servicio...":
            return JsonResponse({'error_message': 'Por favor completa todos los campos antes de realizar la reserva.'})
        
        selected_datetime = datetime.datetime.strptime(fecha, '%Y-%m-%d')
        fecha_formateada = selected_datetime.strftime('%d de %B')

        selected_datetime = datetime.datetime.combine(selected_datetime, datetime.datetime.strptime(hora, "%H:%M").time())
        if selected_datetime > current_datetime:
            validation = True
        else:
            validation = False

        if validation == True:
            start_time = selected_datetime.isoformat()
            end_time = (selected_datetime + datetime.timedelta(minutes=30)).isoformat()
            success = calendar_manager.create_event(servicio + ". " + nombre + ". Contacto: " + telefono, start_time, end_time, "America/Argentina/Buenos_Aires")
            crear_reserva = Reserva(user=user, nombre=nombre, servicio=servicio, fecha=fecha, hora=hora, contacto=telefono)
            crear_reserva.save()
            if success == 200:
                success_message = f"Tu cita fue reservada para el día {fecha_formateada}, a las {hora} horas. Te esperamos."
                return JsonResponse({'success_message': success_message})
            else:
                error_message = "Hubo un error al crear tu cita, por favor inténtalo de nuevo más tarde."
                return JsonResponse({'error_message': error_message})
        else:
            return JsonResponse({'error': 'Ha seleccionado una hora en el pasado, por favor seleccione una nueva' })
            
    if request.method =='GET':
        if not request.user.is_authenticated:
            return render(request, 'reservar.html', {'available_hours':available_hours})
        else:
            return render(request, 'reservar.html', {'apellido':apellido,'nombre':nombre, 'telefono':telefono, 'available_hours':available_hours})
        
@login_required
def mis_reservas(request):
    if request.user.is_authenticated:
        user = request.user
        now = timezone.now()
        reservas = Reserva.objects.filter(user__id=user.id, fecha__gt=now)
        if request.method == 'POST':
            reserva_id = request.POST['reserva_id']
            print('Reserva numero: ', reserva_id)
            reserva = get_object_or_404(Reserva, id=reserva_id, user=user)
            print(reserva)
            reserva.delete()
            return JsonResponse({'message':'Su reserva ha sido eliminada.'})
        return render(request, 'mis_reservas.html',{'reservas':reservas})


def index(request):
    servicios = Servicio.objects.all()
    categorias = Categoria.objects.all()
    context = {'servicios':servicios, 'categorias':categorias}

    if request.method == 'POST':
        buscar = request.POST['buscar']
        print(buscar)
        result = Servicio.objects.filter(nombre__icontains= buscar)
        if not result:
            messages.success(request, ("Producto no encontrado"))

        return render(request, 'index.html', {'servicios':servicios, 'categorias':categorias, 'result':result, 'buscar':str(buscar).capitalize()})

    if request.method =='GET':
        return render(request, 'index.html', context)

def filter_products(request):
    if request.method == 'GET' and 'HTTP_X_REQUESTED_WITH' in request.META and request.META['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest':
        categorias = Categoria.objects.all()
        selected_categories = request.GET.getlist('categories[]')
        print(selected_categories)
        servicios = Servicio.objects.filter(categoria__id__in=selected_categories)
        print(servicios)
        rendered_services = render_to_string('servicios_partial.html', {'servicios': servicios})
        return JsonResponse({'servicios': rendered_services})



def obtener_horas(request):
    if request.method == 'GET' and 'HTTP_X_REQUESTED_WITH' in request.META and request.META['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest':
        fecha_seleccionada = request.GET.get('fecha')
        fecha_seleccionada = datetime.datetime.strptime(fecha_seleccionada, '%Y-%m-%d')
        calendar_manager = google_calendar.GoogleCalendarManager()
        busy_hours, available_hours = calendar_manager.list_busy_available_events(fecha_seleccionada)
        return JsonResponse({'horas_disponibles': available_hours})
    return JsonResponse({'error': 'Método no permitido'})


def servicio(request, pk):
    servicio = Servicio.objects.get(id=pk)
    return render(request, 'servicio.html', {'servicio':servicio})


def categoria(request, foo):
    foo = foo.replace('-',' ')
    if request.method=='GET':
        try:
            categoria = Categoria.objects.get(nombre = foo)
            print(categoria)
            servicios = Servicio.objects.filter(categoria=categoria)
            print(servicios)
            return render(request, 'categorias.html', {"servicios":servicios, "categorias":categoria})
        except:
            messages.success(request, ("La categoría ingresada no existe."))
            return redirect(request, 'index')


def search(request):
    return render(request, 'search.html',{})

def all_services(request):
    all_servicios = Servicio.objects.all()

    servicios_html = render_to_string('servicios_partial.html', {'servicios': all_servicios})

    return JsonResponse({'servicios': servicios_html})

reservadjango/reservadjango/templates/cart_summary.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}Carrito{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'carrito.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Logo -->
  <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="Logo" height="40"></a>
  <!-- Navbar Links -->
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categorias
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/">Todos los productos</a>
                  <!-- Loop through categories and generate dropdown items -->
              </div>
          </li>
      </ul>
  </div>
  <!-- User Dropdown -->
  {% if user.is_authenticated %}
  <div class="dropdown">
      <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.email }}
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'mis_reservas' %}">Mis reservas</a>
          <a class="dropdown-item" href="{% url 'accounts:update_user' %}">Actualizar usuario</a>
          <a class="dropdown-item" href="{% url 'accounts:update_user_info' %}">Informacion del usuario</a>
          <a class="dropdown-item" href="{% url 'payment:billing_info' %}">Información de facturación</a>
          <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
          <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
          </form>
          {% else %}
          <a class="btn btn-danger" href="{% url 'accounts:login' %}">Iniciar sesión</a>
          <a class="btn btn-danger" href="{% url 'accounts:signup' %}">Registrarse</a>
          {% endif %}
      </div>
  </div>
</nav>
<br><br>
<div class="container2">
  <div class="cover2">
      <p>Mi carrito</p>
  </div>
</div>
<div class="form-container">
  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
      {{ message }}
  </div>
  {% endfor %}
</div>
<div class="container_carrito px-3 my-5 clearfix">
    <!-- Shopping cart table -->

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">Productos</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Precio</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">Cantidad</th>
                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                  </tr>
                </thead>
                <tbody>
                  {% for servicio in cart_products %}
                  <tr>
                    <td class="p-4">
                      <div class="media align-items-center">
                        <img src="{{ servicio.imagen.url }}" class="d-block ui-w-40 ui-bordered mr-4" alt="" style="max-width: 200px; max-height: 200px;">
                        <div class="media-body">
                          <a href="#" class="d-block text-dark">{{servicio.nombre}}</a>
                          <small>
                            <span class="text-muted">Descripcion:</span>
                          </small>
                        </div>
                      </div>
                    </td>
                    {% if servicio.descuento %}
                    <td class="text-right font-weight-semibold align-middle p-4">${{servicio.precio_descuento}}</td>
                    {% else %}
                    <td class="text-right font-weight-semibold align-middle p-4">${{servicio.precio}}</td>
                    {% endif %}
                    <td class="align-middle p-4"><select class="form-select form-select-sm w-100" id="select{{servicio.id}}" data-index="{{ servicio.id }}">
                      <option selected>{% for key, value in cantidades.items %}
                        {% if key == servicio.id|slugify %}
                          {{ value }}
                        {% endif %}
                        {% endfor %}
                      </option>
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                  </select></td>
                    <td class="text-center align-middle px-0">
                      <button class="btn btn-link shop-tooltip close float-none text-danger" data-index="{{ servicio.id }}" id="Remove">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
                      </svg>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- / Shopping cart table -->
        
            <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
              <div class="mt-4">
                <label class="text-muted font-weight-normal">Código de descuento</label>
                <input type="text" placeholder="Código" class="form-control">
              </div>
              <div class="d-flex">
                <div class="text-right mt-4 mr-5">
                  <label class="text-muted font-weight-normal m-0">Descuento</label>
                  <div class="text-large"><strong>$20</strong></div>
                </div>
                <div class="text-right mt-4">
                  <label class="text-muted font-weight-normal m-0">Precio total</label>
                  <div class="text-large"><strong>${{totals}}</strong></div>
                </div>
              </div>
            </div>
        
            <div class="float-right">
              <a href="/" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Volver a comprar</a>
              <a href="{% url 'payment:checkout' %}" class="btn btn-lg btn-primary mt-2">Finalizar compra</a>
            </div>
          </div>
      </div>
  </div>
<br><br>
  <script>
    //update cart
    $(document).on('click', '.form-select', function(e){
      var servicio_id = $(this).attr('id').replace('select', '');
      
      $.ajax({
        type:'POST',
        url: "{% url 'cart:cart_update' %}",
        data: {
          servicio_id: servicio_id,
          cantidad: $(this).val(),
          csrfmiddlewaretoken:'{{ csrf_token }}',
          action:'post'
        },
        success: function(json){
        },
        error: function(xhr,errmsg, err){}
      });
    });

    //delete item from cart
    $(document).on('click', '#Remove', function(e){
      //var servicio_id = $(this).attr('id').replace('select', '');
      
      $.ajax({
        type:'POST',
        url: "{% url 'cart:cart_delete' %}",
        data: {
          servicio_id: $(this).data('index'),
          csrfmiddlewaretoken:'{{ csrf_token }}',
          action:'post'
        },
        success: function(json){
          location.reload();
        },
        error: function(xhr,errmsg, err){}
      });
    });
  </script>
  {% endblock %}

reservadjango/reservadjango/templates/categorias.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}Categorias{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ruslan+Display&display=swap">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Logo -->
    <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="Logo" height="40"></a>
    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="d-flex list-unstyled">
            <li class="nav-item2">
                <a class="nav-link" href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="nav-item2 dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categorias
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/">Todos los productos</a>
                </div>
            </li>
            <li class="nav-item2 reservar-hora">
                <a class="nav-link" href="{% url 'reserva' %}">Reservar cita</a>
            </li>
        </ul>
    </div>
    <div class="ml-auto mr-2">
        <button class="btn btn-outline-light" type="button" id="carrito" onclick="window.location.href='{% url 'cart:cart_summary' %}'">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
            </svg>
            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
        </button>
    </div>
    <!-- User Dropdown -->
    {% if user.is_authenticated %}
    <div class="dropdown">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.email }}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'mis_reservas' %}">Mis reservas</a>
            <a class="dropdown-item" href="{% url 'accounts:update_user' %}">Actualizar usuario</a>
            <a class="dropdown-item" href="{% url 'accounts:update_user_info' %}">Informacion del usuario</a>
            <a class="dropdown-item" href="{% url 'payment:billing_info' %}">Información de facturación</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </form>
            {% else %}
            <a class="btn btn-danger" href="{% url 'accounts:login' %}">Iniciar sesión</a>
            <a class="btn btn-danger" href="{% url 'accounts:signup' %}">Registrarse</a>
            {% endif %}
        </div>
    </div>
  </nav>

<br><br>
<!-- TITULOS PRINCIPALES -->
<div class="container2">
    <div class="cover2">
        <p> Categoria: {{categorias.nombre}}</p>
    </div>
</div>

<div class="container" id="servicios">
    <div class="row">
        <div class="col-md-2 " style="margin: 0; padding-left: 0;">
        </div>
        <div class="col-md-10" id="filtered-servicios">
            {% for servicio in servicios %}
                {% if forloop.first or forloop.counter0|divisibleby:5 %}
                <div class="row">
                {% endif %}
                <div class="col-md-2 mb-3">
                    <div class="card">
                        {% if servicio.descuento %}
                        <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem; font-size: 0.8rem;">Oferta</div>
                        {% endif %}
                        <a href="{% url 'servicio_detalle' servicio.pk %}">
                            <img src="{{ servicio.imagen.url }}" class="card-img-top" alt="{{ servicio.nombre }}">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title text-left" style="font-size: 18px;">
                                <a href="{% url 'servicio_detalle' servicio.pk %}" class="text-decoration-none text-dark">{{ servicio.nombre }}</a>
                            </h5>
                            {% if servicio.descuento %}
                            <p class="card-text text-left" style="font-weight: bolder; font-size: 16px;"><strike>${{ servicio.precio }}</strike> &nbsp; ${{ servicio.precio_descuento }}</p>
                            {% else %}
                            <p class="card-text text-left" style="font-weight: bolder; font-size: 16px;">${{ servicio.precio }}</p>
                            {% endif %}
                            <button type="button" value="{{ servicio.id }}" id="add-cart-{{ servicio.id }}" class="btn btn-danger btn-block">Agregar al carrito</button>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:5 or forloop.last %}
                </div>
                {% endif %}
            {% endfor %}
        </div>
            </div>

<div class="container">
    <!-- Rest of your content -->
    <div class="form-container">
        {% for message in messages %}
        <div class="alert alert-secondary" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    <div class="text-container">
        <button type="button" class="btn btn-success mx-auto d-block" style="max-width: 200px;" onclick="window.location.href='/';">Volver al inicio</button>
    </div>


{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'style.js' %}"></script>

</body>
</html>