reservadjango/accounts/urls.py
from django.urls import path
from .views import SignUpView, login_view, email_check, PasswordsChangeView, pass_success, update_user,update_user_info
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name = "signup"),
    path("login/", login_view, name = "login"),

    path("update_user/", update_user, name = "update_user"),
    path("user_info/", update_user_info, name = "update_user_info"),
    
    path("email_check/", email_check, name = "email_check"),
    
    path('password_change/', PasswordsChangeView.as_view(template_name='registration/password_change.html')),
    path('password_change/done/', pass_success),
    

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset.html'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name="password_reset_complete"),
    ]

reservadjango/cart/urls.py
from django.urls import path
from .views import cart_summary, cart_add, cart_delete, cart_update
from django.contrib.auth import views as auth_views

app_name = 'cart'

urlpatterns = [
    path('', cart_summary, name="cart_summary"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    path('update/', cart_update, name="cart_update"),

]

reservadjango/payment/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import TemplateView  # new
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

app_name = 'payment'

urlpatterns = [
    path("payment_success/", views.payment_success, name = "payment_success"),
    path("billing_info/", views.billing_info, name="billing_info"),
    path("checkout/", views.checkout, name="checkout"),
    path("payment_method/", views.payment_method, name="payment_method"),
    path("process_order", views.process_order, name="process_order"),
]

reservadjango/reservadjango/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import TemplateView  # new
from django.contrib.auth.decorators import login_required
from .views import index, servicio, categoria, search, reservar, filter_products, all_services, mis_reservas
from . import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("cart/", include ("cart.urls")),
    path("payment/", include ("payment.urls")),
    path("", index, name="index"),
    path("reserva/", reservar, name="reserva"),
    path("mis_reservas/", mis_reservas, name="mis_reservas"),
    path("obtener_horas/", views.obtener_horas, name="obtener_horas"),
    path("servicio/<int:pk>", servicio, name ="servicio_detalle"),
    path("categoria/<str:foo>", categoria, name = "categoria"),
    path("search/", search, name='search'),
    path("filter_products/", filter_products, name='filter_products'),
    path("all_services/", all_services, name='all_services'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

reservadjango/payment/models.py
from django.db import models
from accounts.models import CustomUser
from reservadjango.models import Servicio
from django.db.models.signals import post_save

class ShippingAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    shipping_nombre = models.CharField(max_length=255)
    shipping_email = models.EmailField(max_length=255)
    shipping_cedula = models.CharField(max_length=255)
    shipping_direccion = models.CharField(max_length=255)
    shipping_ciudad = models.CharField(max_length=255) 

    class Meta:
        verbose_name_plural = "Shipping Address"

    def __str__(self):
        return f'Shipping Address - {str(self.id)}'
    
def create_shipping_address (sender, instance, created, **kwargs):
    if created:
        user_shipping_address = ShippingAddress(user=instance)
        user_shipping_address.save()
post_save.connect(create_shipping_address, sender=CustomUser)

    

class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    shipping_address = models.TextField(max_length=15000)
    precio = models.DecimalField(max_digits=7, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)
    entregado = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'Orden - {str(self.id)}'
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    cantidad = models.PositiveBigIntegerField(default=1)
    precio = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self) -> str:
        return f'Order Item - {str(self.id)} -{str(self.order)}'

reservadjango/payment/forms.py
from django import forms
from .models import ShippingAddress


class Shipping_form(forms.ModelForm):
    shipping_nombre = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre y apellido'}), required=True)
    shipping_email = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email'}), required=True)
    shipping_cedula= forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Cedula'}), required=True)
    shipping_direccion = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Dirección'}), required=True)
    shipping_ciudad = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ciudad'}), required=True)

    class Meta:
        model = ShippingAddress 
        fields = ['shipping_nombre', 'shipping_email','shipping_cedula', 'shipping_direccion','shipping_ciudad',]
        exclude = ['user',]


class PaymentForm(forms.Form):
    metodo_de_pago = forms.ChoiceField(choices=[('1','Retiro en sucursal'),('2','Tarjeta de débito/crédito')], widget=forms.Select(attrs={'class':'form-select', 'placeholder':'Método de pago' }), required=True)
    tarjeta_nombre= forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Titular de la tarjeta'}))
    tarjeta_numero= forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Número tarjeta'}))
    tarjeta_vencimiento= forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Fecha de vencimiento'}))
    cvv= forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Código de seguridad'}))

reservadjango/payment/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView,FormView, TemplateView
from .forms import Shipping_form, PaymentForm
from .models import ShippingAddress, Order, OrderItem
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from accounts.models import CustomUser, Profile
from reservadjango.models import Servicio
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from cart.cart import Cart


# Create your views here.
def payment_success(request):
    render (request, "payments/payment_success.html",{})



@login_required
def billing_info(request):
    if request.user.is_authenticated:
        current_user = ShippingAddress.objects.get(user__id=request.user.id)
        shipping_form = Shipping_form(request.POST or None, instance=current_user)

        if shipping_form.is_valid():
            shipping_form.save()
            messages.success(request, "Tu informacion de facturacion se ha actualizado.")
            return redirect('index')
        return render(request, 'payments/billing_info.html', {'shipping_form':shipping_form})
    else:
        messages.success(request, "Debes iniciar sesion para acceder a esta página.")
        return redirect('index')
    


def checkout(request):
    cart = Cart(request)
    cart_products = cart.get_products
    cantidades = cart.get_cantidades
    totals = cart.cart_total()

    if request.user.is_authenticated:
        current_user = ShippingAddress.objects.get(user__id=request.user.id)
        form = Shipping_form(request.POST or None, instance=current_user) 
        return render(request, "payments/checkout.html",{'cart_products':cart_products, "cantidades":cantidades, "totals":totals, "form":form})

    else:
        #checkout sin usuario
        form = Shipping_form(request.POST or None)
        return render(request, "payments/checkout.html",{'cart_products':cart_products, "cantidades":cantidades, "totals":totals, "form":form})
    

def payment_method(request):
    if request.POST:
        cart = Cart(request)
        totals = cart.cart_total()
        
        #create session with billing info

        my_shipping = request.POST
        request.session['my_shipping']= my_shipping

        if request.user.is_authenticated:
            #checkear si esta logeado y obtener la informacion de pago

            billing_form = PaymentForm()
            return render(request, "payments/method.html", {"totals": totals, "shipping_info":request.POST, "billing_form":billing_form})
        else:
            billing_form = PaymentForm()
            return render(request,"payments/method.html", {"totals": totals, "shipping_info":request.POST, "billing_form":billing_form})
        
    else:
        messages.success(request, "Acceso denegado.")
        return redirect('index')
    

def process_order(request):
    if request.POST:
        cart = Cart(request)
        cart_products = cart.get_products()
        cantidades = cart.get_cantidades()
        totals = cart.cart_total()
        metodo = request.POST.get('metodo_de_pago')
        payment_form = PaymentForm(request.POST or None)
        #get shipping session data
        my_shipping = request.session.get('my_shipping')

        #generar Order info
        
        full_name = my_shipping['shipping_nombre']
        email = my_shipping['shipping_email']
        precio = totals
        shipping_address = f"Nombre: {my_shipping['shipping_nombre']}\nEmail: {my_shipping['shipping_email']}\nCI: {my_shipping['shipping_cedula']}\nDirección: {my_shipping['shipping_direccion']}\nCiudad: {my_shipping['shipping_ciudad']}\nMétodo de pago: {metodo}"


        if request.user.is_authenticated:
            user = request.user
            #CREAR ORDEN
            create_order = Order(user=user,nombre=full_name, email=email, shipping_address=shipping_address, precio=precio)
            create_order.save()

            #AGREGAR ORDER ITEMS
            #get order id
            order_id = create_order.pk
            for servicio in cart_products:
                servicio_id = servicio.id
                if servicio.descuento:
                    servicio_precio = servicio.precio_descuento
                else:
                    servicio_precio = servicio.precio
                
                for key, value in cantidades.items():
                    if int(key) == servicio_id:
                        create_order_item = OrderItem(order_id=order_id, servicio_id=servicio_id, user=user, cantidad=value, precio=servicio_precio)
                        create_order_item.save()
            #delete cart
            for key in list(request.session.keys()):
                if key == "session_key":
                    del request.session[key]
                        

        else:
            create_order = Order(nombre=full_name, email=email, shipping_address=shipping_address, precio=precio)
            create_order.save()
             #AGREGAR ORDER ITEMS
            #get order id
            order_id = create_order.pk
            for servicio in cart_products():
                servicio_id = servicio.id
                if servicio.descuento:
                    servicio_precio = servicio.precio_descuento
                else:
                    servicio_precio = servicio.precio
                
                for key, value in cantidades().items():
                    if int(key) == servicio_id:
                        create_order_item = OrderItem(order_id=order_id, servicio_id=servicio_id, cantidad=value, precio=servicio_precio)
                        create_order_item.save()

            for key in list(request.session.keys()):
                if key == "session_key":
                    del request.session[key]

        messages.success(request, f"Orden creada. Orden número {order_id}.")
        return redirect('index')

reservadjango/payment/templates/payments/billing_info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}Información de facturación{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'passwordmng.css' %}">
</head>

<link rel="stylesheet" href="/reservadjango/static/passwordmng.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ruslan+Display&display=swap">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Logo -->
    <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="Logo" height="40"></a>
    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Inicio</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categorias
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/">Todos los productos</a>
                    <!-- Loop through categories and generate dropdown items -->
                </div>
            </li>
        </ul>
    </div>
    <!-- User Dropdown -->
    {% if user.is_authenticated %}
    <div class="dropdown">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.email }}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'index' %}">Inicio</a>
            <a class="dropdown-item" href="{% url 'accounts:update_user' %}">Actualizar usuario</a>
            <a class="dropdown-item" href="{% url 'accounts:update_user_info' %}">Información del usuario</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </form>
            {% else %}
            <a class="btn btn-danger" href="{% url 'accounts:login' %}">Iniciar sesión</a>
            <a class="btn btn-danger" href="{% url 'accounts:signup' %}">Registrarse</a>
            {% endif %}
        </div>
    </div>
</nav>

<br><br>
<!-- TITULOS PRINCIPALES -->
<div class="container2">
    <div class="cover2">
        <p>Información de facturación</p>
    </div>
</div>
<br>

<div class="container">
    <div class="form-container">
        {% for message in messages %}
        <div class="alert alert-secondary" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        <form method="post" action="{% url 'payment:billing_info' %}" id="miFormulario">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_shipping_nombre">Nombre y aprellido</label>
                {{ shipping_form.shipping_nombre }}
            </div>
            <div class="form-group">
                <label for="id_shipping_email">Email</label>
                {{ shipping_form.shipping_email }}
            </div>
            <div class="form-group">
                <label for="id_shipping_direccion">Direccion</label>
                {{ shipping_form.shipping_direccion }}
            </div>
            <div class="form-group">
                <label for="id_shipping_cedula">Cédula de identidad</label>
                {{ shipping_form.shipping_cedula }}
            </div>
            <div class="form-group">
                <label for="id_shipping_ciudad">Ciudad</label>
                {{ shipping_form.shipping_ciudad }}
            </div>

            <div class="button-container">
                <button id="boton" type="submit" class="btn btn-success">Siguiente</button>
            </div>            
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</body>
</html>

reservadjango/payment/templates/payments/checkout.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}Finalizar compra{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'carrito.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Logo -->
  <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="Logo" height="40"></a>
  <!-- Navbar Links -->
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categorias
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/">Todos los productos</a>
                  <!-- Loop through categories and generate dropdown items -->
              </div>
          </li>
      </ul>
  </div>
  <!-- User Dropdown -->
  {% if user.is_authenticated %}
  <div class="dropdown">
      <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.email }}
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'accounts:update_user' %}">Actualizar usuario</a>
          <a class="dropdown-item" href="{% url 'accounts:update_user_info' %}">Informacion del usuario</a>
          <a class="dropdown-item" href="{% url 'payment:billing_info' %}">Información de facturación</a>
          <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
          <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
          </form>
          {% else %}
          <a class="btn btn-danger" href="{% url 'accounts:login' %}">Iniciar sesión</a>
          <a class="btn btn-danger" href="{% url 'accounts:signup' %}">Registrarse</a>
          {% endif %}
      </div>
  </div>
</nav>
<br><br>
<div class="container2">
  <div class="cover2">
      <p>Finalizar compra</p>
  </div>
</div>
<div class="form-container">
  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
      {{ message }}
  </div>
  {% endfor %}
</div>
<br><br>
<div class="container_carrito row">
    <div class="col-md-8 ">
        <div class="card">
            <div class="card-header bg-dark text-white">
            Datos de facturación
            </div>
            <form method="POST" action="{% url 'payment:payment_method' %}">
                {% csrf_token %}
            <div class="card-body">
                {{form.as_p}}
                <div class="button-container">
                    <button type="submit" class="btn btn-secondary">Continuar</button>
                </div>            
            </div>
            </form>
        </div>    
    </div>
    <div class="col-md-4 ">
        <div class="card">
            <div class="card-header">
            Detalles del pedido
            </div>
            <div class="card-body">
                {% for servicio in cart_products %}
                    <div class="product-card" onclick="window.location='{% url 'servicio_detalle' servicio.pk %}'">
                        <img src="{{ servicio.imagen.url }}" class="card-img-left" alt="{{ servicio.nombre }}">
                        <div class="product-info">
                            <div class="product-header">
                                <p class="small">{{ servicio.nombre }}</p>
                                <p class="price">
                                    {% if servicio.descuento %}
                                        ${{ servicio.precio_descuento }}
                                    {% else %}
                                        ${{ servicio.precio }}
                                    {% endif %}
                                </p>
                            </div>
                            <p class="small">Cantidad:
                                {% for key, value in cantidades.items %}
                                    {% if key == servicio.id|slugify %}
                                        {{ value }}
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                {% endfor %}
                <div class="total-container">
                    <a href="{% url 'cart:cart_summary' %}" class="btn btn-sm btn-outline-secondary">Modificar carrito</a>
                    <p class="total"><strong>Total: {{ totals }}</strong></p>
                </div>
            </div>
        </div>        
    </div>
</div>


  {% endblock %}

reservadjango/payment/templates/payments/method.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <title>{% block title %}Pagar{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'carrito.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Logo -->
  <a class="navbar-brand" href="/"><img src="{% static 'logo.png' %}" alt="Logo" height="40"></a>
  <!-- Navbar Links -->
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categorias
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/">Todos los productos</a>
                  <!-- Loop through categories and generate dropdown items -->
              </div>
          </li>
      </ul>
  </div>
  <!-- User Dropdown -->
  {% if user.is_authenticated %}
  <div class="dropdown">
      <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.email }}
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'accounts:update_user' %}">Actualizar usuario</a>
          <a class="dropdown-item" href="{% url 'accounts:update_user_info' %}">Informacion del usuario</a>
          <a class="dropdown-item" href="{% url 'payment:billing_info' %}">Información de facturación</a>
          <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
          <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
          </form>
          {% else %}
          <a class="btn btn-danger" href="{% url 'accounts:login' %}">Iniciar sesión</a>
          <a class="btn btn-danger" href="{% url 'accounts:signup' %}">Registrarse</a>
          {% endif %}
      </div>
  </div>
</nav>
<br><br>
<div class="container2">
  <div class="cover2">
      <p>Pagar</p>
  </div>
</div>
<div class="form-container">
  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
      {{ message }}
  </div>
  {% endfor %}
</div>
<br><br>
<div class="container_carrito row">
    <div class="col-md-8 ">
        <div class="card">
            <div class="card-header bg-dark text-white">
            Datos de facturación
            </div>
            <div class="card-body">
                <p>Nombre: {{shipping_info.shipping_nombre}}</p>
                <p>Email: {{shipping_info.shipping_email}}</p>
                <p>Cédula de identidad: {{shipping_info.shipping_cedula}}</p>
                <p>Dirección: {{shipping_info.shipping_direccion}}</p>
                <form method="POST" action="{% url 'payment:process_order' %}">
                    {% csrf_token %}
                    {{ billing_form.as_p}}
                
                    <script>
                        document.addEventListener('DOMContentLoaded', function() {
                          var paymentMethodField = document.getElementById('id_metodo_de_pago');
                          var tarjetaNombreField = document.getElementById('id_tarjeta_nombre');
                          var tarjetaNumeroField = document.getElementById('id_tarjeta_numero');
                          var tarjetaVencimientoField = document.getElementById('id_tarjeta_vencimiento');
                          var cvvField = document.getElementById('id_cvv');
                        
                          // Function to disable or enable additional fields based on selected payment method
                          function toggleAdditionalFields() {
                            if (paymentMethodField.value === '2') {
                              tarjetaNombreField.removeAttribute('disabled');
                              tarjetaNumeroField.removeAttribute('disabled');
                              tarjetaVencimientoField.removeAttribute('disabled');
                              cvvField.removeAttribute('disabled');
                            } else {
                              tarjetaNombreField.setAttribute('disabled', 'disabled');
                              tarjetaNumeroField.setAttribute('disabled', 'disabled');
                              tarjetaVencimientoField.setAttribute('disabled', 'disabled');
                              cvvField.setAttribute('disabled', 'disabled');
                            }
                          }
                        
                          // Call the function initially and whenever the payment method field changes
                          toggleAdditionalFields();
                          paymentMethodField.addEventListener('change', toggleAdditionalFields);
                        });
                        </script>
                <div class="button-container">
                    <button type="submit" class="btn btn-secondary">Pagar</button>
                </div>     
                </form>       
            </div>
        </div>    
    </div>
    <div class="col-md-4 ">
        <div class="card">
            <div class="card-header">
            Detalles del pedido
            </div>
            <div class="card-body">
                <div class="total-container">
                    <a href="{% url 'payment:checkout' %}" class="btn btn-sm btn-outline-secondary">Volver atrás</a>
                    <p class="total"><strong>Total: {{ totals }}</strong></p>
                </div>
            </div>
        </div>        
    </div>
</div>


  {% endblock %}

reservadjango/payment/templates/payments/payment_success.html
<h1>Payment success</h1>

reservadjango/payment/templates/payments/process_order.html
<h1>Test</h1>